version: "3"
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: hoomnayangi
    container_name: hoomnayangi_db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
