version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: hoomnayangi
    container_name: hoomnayangi_db
    ports:
      - 15432:5432
